export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const SORT = 'SORT';

export const SET_CURRENT_SORT = 'SET_CURRENT_SORT';

export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_SEARCH_TIMER = 'SET_SEARCH_TIMER';

export const TOGGLE_CART = 'TOGGLE_CART';
export const TOGGLE_CATALOG = 'TOGGLE_CATALOG';
export const TOGGLE_SIGNUP = 'TOGGLE_SIGNUP';

export const SET_SIGNUP_FORM_FIELD_VALUE = 'SET_SIGNUP_FORM_FIELD_VALUE';
export const UPDATE_FIELDS = 'UPDATE_FIELDS';
export const EMPTY_FORM_INPUT = 'EMPTY_FORM_INPUT';
